fix: dpr srcset when only h param
imgix/imgix-php pull request #76
Opened 2021-03-08 15:06 UTC by luqven

# Description
This PR ensures a DPR-based SrcSet is generated when a fixed height is the only parameter value.

It removes tests that no longer apply to only having h as a param, and
adds tests that ensure the DPR `sercset` was generated correctly.

2021-03-08 15:15 UTC, frederickfogerty approved these changes
LGTM 👏

2021-03-08 19:07 UTC, ericdeansanchez commented
👍

2021-03-09 01:38 UTC, sherwinski approved these changes

2021-03-09 01:41 UTC, sherwinski requested changes
I just remembered that this change also needs to be reflected in the project [documentation](https://github.com/imgix/imgix-php#fixed-width-images) at some point, either in this PR or a separate one.

2021-03-10 01:14 UTC, merged